# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71b6c472aad682759d9c3b44502562eb046150d090056695b58ce8c7182fb5ddae018be3c07299dd627c26975ca41ad199e8a80494dd768b3d7b66201c33d213

test:
  secret_key_base: c8e919071501b5df01b6f4abcbebef9900684cebab4e64ed31d8de9203d23ceb908a4fde310526c64da6a4106edd92588c2db8a35495f5b02e46fa08fc1c54c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
